version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: projectSpring
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - /home/darlei/Documents/volumes_docker
    ports:
      - "5432:5432"
    init: true